<a href="https://colab.research.google.com/github/danish123-a/Data_Loader./blob/main/Data_Loader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from sklearn.datasets import make_classification

In [8]:
x,y=make_classification(
                         n_samples=10,
                         n_classes=2,
                         n_informative=2,
                         n_features=2,
                         n_redundant=0,
                         random_state=42
)

In [9]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [10]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [19]:
import torch as t

In [20]:
x_t=t.tensor(x)

In [21]:
y_t=t.tensor(y)

In [22]:
x_t

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]], dtype=torch.float64)

In [23]:
y_t

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [30]:
from torch.utils.data import Dataset, DataLoader


In [61]:
class Custom_dataset(Dataset):
  def __init__(self,features,label):
    self.features=features
    self.label=label
  def __len__(self):
    return self.features.shape[0]
  def __getitem__(self, index):
    return self.features[index],self.label[index]



In [62]:
dataset=Custom_dataset(x_t,y_t)

In [63]:
len(dataset)

10

In [64]:
print(dataset.__init__(x_t,y_t))

None


In [65]:
dataset[2]

(tensor([-2.8954,  1.9769], dtype=torch.float64), tensor(0))

In [66]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [67]:
for batch_features,batch_label in dataloader:
  print(batch_features)
  print(batch_label)
  print("*"*50)


tensor([[ 1.8997,  0.8344],
        [-0.7206, -0.9606]], dtype=torch.float64)
tensor([1, 0])
**************************************************
tensor([[-1.9629, -0.9923],
        [-1.1402, -0.8388]], dtype=torch.float64)
tensor([0, 0])
**************************************************
tensor([[-0.9382, -0.5430],
        [-2.8954,  1.9769]], dtype=torch.float64)
tensor([1, 0])
**************************************************
tensor([[ 1.7273, -1.1858],
        [ 1.0683, -0.9701]], dtype=torch.float64)
tensor([1, 1])
**************************************************
tensor([[ 1.7774,  1.5116],
        [-0.5872, -1.9717]], dtype=torch.float64)
tensor([1, 0])
**************************************************
